#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect the requirements:
#+ Install nginx
#+ Nginx should be listening on port 80
#+ When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx start
