#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo mkdir /usr/share/nginx/html
sudo touch /usr/share/nginx/html/index.html
sudo echo "Hello World!" > /usr/share/nginx/html/index.html
sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /usr/share/nginx/html;
     index       index.html index.htm;
}

location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx start
