#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" |  sudo tee /etc/nginx/html/404.html
sudo printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

service nginx restart
